config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("users/", include("users.urls", namespace="users")),
    path("orders/", include("orders.urls", namespace="orders")),
    path("deliveries/", include("deliveries.urls", namespace="deliveries")),
    path("restaurant/", include("restaurants.urls", namespace="restaurants")),
    path("api-auth/", include("rest_framework.urls", namespace="rest_framework")),
]

restaurants/urls.py
from django.urls import path
from . import views

app_name = "restaurants"

urlpatterns = [
    path("orders/<int:shop_pk>", views.order_list, name="order_list"),
    path("time-input/", views.time_input, name="time_input"),
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("user/", views.user, name="user"),
    path("login/", views.login, name="login"),
]

restaurants/views.py
from django.shortcuts import redirect, render
from django.contrib import messages
from django.views.decorators.csrf import csrf_exempt
from django.urls import reverse
from django.http import HttpResponse
from orders.models import Order, Shop


@csrf_exempt
def order_list(request, shop_pk):
    if request.method == "GET":
        order_list = Order.objects.filter(shop=shop_pk)
        shop = Shop.objects.get(pk=shop_pk)
        return render(
            request,
            "restaurant/restaurant_order_list.html",
            {"order_list": order_list, "shop": shop},
        )
    else:
        return HttpResponse(status=404)


def time_input(request):
    if request.method == "POST":
        estimated_time = request.POST.get("estimated_time")
        order_id = int(request.POST.get("order_id"))
        order_item = Order.objects.get(pk=order_id)
        shop_pk = order_item.shop.pk
        order_item.estimated_time = estimated_time
        order_item.save()
        messages.success(request, "Estimating time is changed")
        return redirect(reverse("restaurants:order_list", kwargs={"shop_pk": shop_pk}))
    else:
        return HttpResponse(status=404)

templates/restaurant/restaurant_order_list.html
{% extends 'base.html' %}

{% block content %}
<div class="container mx-auto mt-10 flex flex-col items-center">
    <div class="text-3xl mb-10">Order list for {{shop.shop_name}}</div>
    <div class="grid grid-cols-3 gap-5">
        {% for order in order_list %}
            <div class="border border-gray-400 p-10">
                <div class="flex items-center text-2xl mb-3">
                    <ul>
                    {% for food in order.order_food_lists.all %}
                        <li class="mr-1 text-green-700">{{food.food_name}}</li>
                    {% endfor %}
                    </ul>
                </div>
                <div>Order Date : {{order.order_date}}</div>
                <div>Address : {{order.address}}</div>
                
                <div class="flex items-center">
                    <div class="mr-2">Estimate Time : </div>
                    {% if order.estimated_time == -1 %}
                        <div>
                            <form action="{% url 'restaurants:time_input' %}" method="POST">
                                {% csrf_token %}
                                <input type="number" name="estimated_time" id="" class="border border-gray-500 rounded outline-none w-20"> minutes
                                <input type="hidden" name="order_id" value="{{order.id}}">
                                <button class="bg-gray-400 text-white rounded p-1 text-sm">Update</button>
                            </form>
                        </div>
                    {% else %}
                        <div class="text-blue-400">{{order.estimated_time}} minutes</div>
                    {% endif %}
                </div>
                <div>Status : 
                    <span class="text-red-400">{% if order.deliver_finished %}Finished{% else %}Delivering{% endif %}</span>
                </div>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock content %}