config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("users/", include("users.urls", namespace="users")),
    path("orders/", include("orders.urls", namespace="orders")),
    path("deliveries/", include("deliveries.urls", namespace="deliveries")),
    path("restaurant/", include("restaurants.urls", namespace="restaurants")),
    path("api-auth/", include("rest_framework.urls", namespace="rest_framework")),
]

orders/urls.py
from django.urls import path
from . import views

app_name = "orders"

urlpatterns = [
    path("shops/", views.shop, name="shop"),
    path("menus/<int:pk>", views.menu, name="menu"),
    path("order/", views.order, name="order"),
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("user/", views.user, name="user"),
    path("login/", views.login, name="login"),
]

orders/models.py
from django.db import models


class Shop(models.Model):
    shop_name = models.CharField(max_length=50)
    shop_address = models.CharField(max_length=100)

    def __str__(self):
        return self.shop_name


class Menu(models.Model):
    food_name = models.CharField(max_length=20)
    shop = models.ForeignKey(Shop, related_name="menus", on_delete=models.CASCADE)

    def __str__(self):
        return self.food_name


class Order(models.Model):
    address = models.CharField(max_length=120)
    order_date = models.DateTimeField("date ordered")
    estimated_time = models.IntegerField(default=-1)
    deliver_finished = models.BooleanField(default=False)
    shop = models.ForeignKey(Shop, related_name="orders", on_delete=models.CASCADE)

    def __str__(self):
        return f"Address: {self.address} Shop: {self.shop.shop_name}"


class OrderFoodList(models.Model):
    food_name = models.CharField(max_length=20)
    order = models.ForeignKey(
        Order, related_name="order_food_lists", on_delete=models.CASCADE
    )

    def __str__(self):
        return self.food_name

orders/views.py
from django.urls import reverse
from django.utils import timezone
from django.contrib import messages
from django.shortcuts import redirect, render
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from rest_framework.parsers import JSONParser
from orders.models import OrderFoodList, Shop, Menu, Order
from users.models import User
from orders.serializers import MenuSerializer, ShopSerializer


@csrf_exempt
def shop(request):
    if request.method == "GET":
        # serializer = ShopSerializer(shops, many=True)
        # return JsonResponse(serializer.data, safe=False)
        try:
            user_id = request.session["user_id"]
            if user_id is not None:
                user = User.objects.get(pk=user_id)
                if user.user_type == User.CUSTOMER:
                    shops = Shop.objects.all()
                    return render(request, "order/shop_list.html", {"shop_list": shops})
                else:
                    messages.warning(request, "You can't access this page")
                    return redirect("users:login")
        except KeyError:
            messages.warning(request, "You can't access this page")
            return redirect("users:login")

    elif request.method == "POST":
        data = JSONParser().parse(request)
        serializer = ShopSerializer(data=data)
        if serializer.is_valid():
            serializer.save()
            return JsonResponse(serializer.data, status=201)
        return JsonResponse(serializer.errors, status=400)


@csrf_exempt
def menu(request, pk):
    if request.method == "GET":
        menus = Menu.objects.filter(shop=pk)

        # serializer = MenuSerializer(menus, many=True)
        # return JsonResponse(serializer.data, safe=False)

        return render(
            request, "order/menu_list.html", {"menu_list": menus, "shop_pk": pk}
        )

    elif request.method == "POST":
        data = JSONParser().parse(request)
        serializer = MenuSerializer(data=data)
        if serializer.is_valid():
            serializer.save()
            return JsonResponse(serializer.data, status=201)
        return JsonResponse(serializer.errors, status=400)


@csrf_exempt
def order(request):
    if request.method == "POST":
        address = request.POST.get("address")
        shop = int(request.POST.get("shop"))
        food_list = request.POST.getlist("menu")
        order_date = timezone.now()
        shop_item = Shop.objects.get(pk=shop)
        shop_item.orders.create(address=address, order_date=order_date, shop=int(shop))
        order_item = Order.objects.get(pk=shop_item.orders.latest("pk").pk)
        for food in food_list:
            order_item.order_food_lists.create(food_name=food)
        messages.success(request, "Success to order")
        return redirect(reverse("orders:order"))

    elif request.method == "GET":
        order_list = Order.objects.all()
        order_item = OrderFoodList.objects.all()
        return render(
            request,
            "order/order_list.html",
            {"order_list": order_list, "order_item": order_item},
        )

templates/order/menu_list.html
{% extends 'base.html' %}

{% block content %}
<div class="container mx-auto mt-10">
    <form method="POST" action="{% url 'orders:order' %}">
        <div class="mb-5">
            <div class="text-3xl mb-5">1. Choose the menu</div>
            {% for menu in menu_list %}
                <div class="mb-2">
                    <input type="checkbox" id="menu_{{forloop.counter}}" name="menu" value="{{menu.food_name}}">
                    <label for="menu_{{forloop.counter}}" class="cursor-pointer">{{menu.food_name}}</label>
                </div>
            {% endfor %}
        </div>
        <div>
            <div class="text-3xl mb-5">2. Write your address</div>
            <input type="hidden" name="shop" value="{{shop_pk}}">
            <input type="text" name="address" required placeholder="Address" class="border border-gray-400 rounded py-2 px-5 outline-none w-96">
        </div>
        <button class="mt-5 bg-blue-400 py-2 px-5 rounded hover:opacity-70 text-white">Order</button>
    </form>
</div>
{% endblock content %}

templates/order/order_list.html
{% extends 'base.html' %}

{% block content %}
<div class="container mx-auto mt-10 flex flex-col items-center">
    <div class="text-3xl mb-10">Order List for Customer</div>
    <div class="grid grid-cols-3 gap-5">
        {% for order in order_list %}
            <div class="border border-gray-400 p-10">
                <div class="text-center text-2xl mb-3">{{order.shop.shop_name}}</div>
                <div>Order Date : {{order.order_date}}</div>
                <div>Address : {{order.address}}</div>
                <div class="flex items-center">
                    <div class="mr-2">Menu : </div>
                    {% for food in order.order_food_lists.all %}
                        <div class="mr-1">{{food.food_name}}</div>
                    {% endfor %}
                </div>
                <div>Estimate Time : 
                    <span class="text-blue-500 font-medium">{% if order.estimated_time == -1 %}Undefined{% else %}{{order.estimated_time}} minutes{% endif %}</span>
                </div>
                <div>Status : {% if order.deliver_finished %}Finished{% else %}Delivering{% endif %}</div>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock content %}

templates/order/shop_list.html
{% extends 'base.html' %}

{% block content %}
    <div class="container mx-auto grid grid-cols-3 gap-2 mt-10">
        {% for shop in shop_list %}
            <div class="border border-gray-300 p-10 text-center">
                <a class="text-3xl hover:text-blue-400" href="{% url 'orders:menu' shop.pk %}">{{shop.shop_name}}</a>
                <div>{{shop.shop_address}}</div>
            </div>
        {% endfor %}
    </div>
{% endblock content %}